version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: de-task-frontend
    ports:
      - 3001:3000
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"