version: '3.8'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: de-task-clickhouse
    env_file:
      - ./.env.prd
    volumes:
      - clickhouse-data:/var/lib/clickhouse/
      - clickhouse-logs:/var/log/clickhouse-server/
      - ./clickhouse/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    env_file:
      - ./.env.prd
    depends_on:
      - clickhouse
      - kafka
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  nginx:
    image: nginx:latest
    container_name: de-task-nginx
    volumes:
      - ./nginx/app_lb.conf:/etc/nginx/nginx.conf
    ports:
      - "8088:80"
    depends_on:
      - api
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: de-task-zookeeper
    env_file:
      - ./.env.dev
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  kafka:
    image: wurstmeister/kafka
    container_name: de-task-kafka
    env_file:
      - ./.env.dev
    healthcheck:
      test: ["CMD", "kafka-topics.sh", "--list", "--zookeeper", "zookeeper:2181"]
      interval: 5s
      timeout: 10s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  
  frontend:
    container_name: de-task-frontend
    image: de-task-frontend
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - 8099:80
    env_file:
      - ./.env.prd
    restart: always
    volumes:
      - ./nginx/frontend.conf:/etc/nginx/nginx.conf

volumes:
  clickhouse-data:
  clickhouse-logs:
