version: '3.8'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: de-task-clickhouse
    ports:
      - 8123:8123
      - 9000:9000
    env_file:
      - ./.env.prd
    volumes:
      - clickhouse-data:/var/lib/clickhouse/
      - clickhouse-logs:/var/log/clickhouse-server/
      - ./clickhouse/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: de-task-api
    ports:
      - "8000:8000"
    env_file:
      - ./.env.prd
    depends_on:
      - clickhouse
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  nginx:
    image: nginx:latest
    container_name: de-task-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    depends_on:
      - api
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: de-task-zookeeper
    ports:
      - "2181:2181"
    env_file:
      - ./.env.dev
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  kafka:
    image: wurstmeister/kafka
    container_name: de-task-kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    env_file:
      - ./.env.dev
    healthcheck:
      test: ["CMD", "kafka-topics.sh", "--list", "--zookeeper", "zookeeper:2181"]
      interval: 5s
      timeout: 10s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  clickhouse-data:
  clickhouse-logs:
