FROM python:3.9-slim

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .

COPY entrypoint.dev.sh /opt/entrypoint.dev.sh
RUN chmod +x /opt/entrypoint.dev.sh

ENTRYPOINT ["/opt/entrypoint.dev.sh"]
